DROP DATABASE IF EXISTS review_service;
DROP USER IF EXISTS `review_service`@`%`;
CREATE DATABASE IF NOT EXISTS review_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `review_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `review_service`.* TO `review_service`@`%`;
FLUSH PRIVILEGES;